services:
  - type: web
    name: totf-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: totf-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: RENDER
        value: true

databases:
  - name: totf-db
    databaseName: totfdb
    user: totfuser