services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: your-app-db
    databaseName: your_db_name
    user: your_db_user