services:
  - type: web
    name: totf-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: totf-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: totf-db
    plan: free
    databaseName: totfdb
    user: totfuser