# Generated by Django 5.1.1 on 2025-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("totfapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="sync_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
